<?php

namespace App\Filament\Resources\ItemResource\Pages;

use App\Enums\AccRef;
use App\Filament\Resources\ItemResource;
use App\Livewire\Traits\AccTrait;
use App\Models\Barcode;
use App\Models\Item;
use App\Models\Place;
use App\Models\Place_stock;
use App\Models\Price_buy;
use App\Models\Setting;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\Auth;

class CreateItem extends CreateRecord
{
    use AccTrait;
    protected static string $resource = ItemResource::class;
    protected static bool $canCreateAnother = false;
    protected ?string $heading="";

    protected function mutateFormDataBeforeCreate(array $data): array
    {

        $data['user_id'] = auth()->id();
        $data['stock']=$data['balance'];
        $data['price_cost']=$data['price_buy'];



        return $data; // TODO: Change the autogenerated stub
    }
    protected function afterCreate(): void
    {
        if ($this->data['balance'] && $this->data['balance'] > 0) {
            Place_stock::insert([
                'item_id'=>Item::max('id'),
                'place_id'=> $this->data['place_id'],
                'stock'=>$this->data['balance'],
            ]);
            $Item=Item::find(Item::max('id'));
            $place=Place::find($this->data['place_id']);
            $this->AddKyde($place->account->id,AccRef::makzoone->value,$Item,$this->data['price_buy']*$this->data['balance'],now(),'مخزون بداية المدة');
        }
    }
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('create');
    }
}
