<?php

namespace App\Filament\Resources\HallTranResource\Pages;

use App\Filament\Resources\HallTranResource;
use App\Models\Hall_stock;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateHallTran extends CreateRecord
{
    protected static string $resource = HallTranResource::class;
    protected ?string $heading='نقل منتجات';
    protected static bool $canCreateAnother = false;

    protected function getRedirectUrl(): string
    {
        return static::getResource()::getUrl('index');
    }
    protected function mutateFormDataBeforeCreate(array $data): array
    {

        $h=Hall_stock::where('hall_id', $data['hall_id1'])
            ->where('product_id',$data['product_id'])->first();
        $h->stock -= $data['quant'];
        $h->save();
        $h=Hall_stock::where('hall_id', $data['hall_id2'])
            ->where('product_id',$data['product_id'])->first();
        if ($h) {
            $h->stock += $data['quant'];
            $h->save();
        } else
            Hall_stock::create([
                'hall_id'=>$data['hall_id2'],
                'product_id'=>$data['product_id'],
                'stock'=>$data['quant'],
            ]);

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

}
