<?php

namespace App\Filament\Resources\SalaryResource\Pages;

use App\Enums\AccRef;
use App\Filament\Resources\SalaryResource;
use App\Livewire\Traits\AccTrait;
use App\Models\Salary;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateSalary extends CreateRecord
{
    use AccTrait;
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('create');
    }
    public static ?string $title = 'ادخال مرتب';
    protected static string $resource = SalaryResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['status'] = 1;
        $data['raseed'] = 0;
        return $data; // TODO: Change the autogenerated stub
    }

}
