<?php

namespace App\Filament\Resources\RecsuppResource\Pages;

use App\Enums\AccRef;
use App\Filament\Resources\RecsuppResource;
use App\Livewire\Traits\AccTrait;
use App\Models\Acc;
use App\Models\Buy;
use App\Models\Kazena;
use App\Models\Place;
use App\Models\Receipt;
use App\Models\Recsupp;
use App\Models\Supplier;
use Filament\Actions;
use Filament\Forms\Get;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;

class EditRecsupp extends EditRecord
{
  use AccTrait;
  protected static string $resource = RecsuppResource::class;
  protected ?string $heading='';

 public $buy_to_save;
 public $rec_who;
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
    protected function mutateFormDataBeforeSave(array $data): array
  {
      if ($this->rec_who == 3 || $this->rec_who == 4 || $this->rec_who == 5 || $this->rec_who == 6)
         $this->buy_to_save=$data['buy_id'];
      $this->rec_who=$data['rec_who'];

    return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
  }

  protected function beforeSave(): void {
      $rescupp=Recsupp::find($this->data['id']);
      $supp=Supplier::find($this->data['supplier_id']);

      if ($rescupp->kyde)
          foreach ($rescupp->kyde as $rec) $rec->delete();

      if ($rescupp->kazena_id) $nakd=Kazena::find($rescupp->kazena_id);
      else $nakd=Acc::find($rescupp->acc_id);
      if ($rescupp->imp_exp->value==0)
          $this->AddKyde($nakd->account->id,$supp->account->id,
              $rescupp,$this->data['val'],$this->data['receipt_date'],'من الموردين الي النقدية');
      else
          $this->AddKyde($supp->account->id,$nakd->account->id,
              $rescupp,$this->data['val'],$this->data['receipt_date'],'من النقدية الي الموردين');


  }
  protected function afterSave(): void
    {
        if ($this->rec_who == 3 || $this->rec_who == 4 || $this->rec_who == 5 || $this->rec_who == 6)
        {

            $imp=Recsupp::where('buy_id',$this->buy_to_save)->whereIn('rec_who',[3,6])
                ->sum('val');
            $exp=Recsupp::where('buy_id',$this->buy_to_save)->whereIn('rec_who',[4,5])
                ->sum('val');
            $buy=Buy::find($this->buy_to_save);
            $buy->pay=$exp-$imp;

            $buy->save();
        }
    }

    protected function getHeaderActions(): array
    {
        return [
            //
        ];
    }
}
