<?php

namespace App\Filament\Resources\BuyResource\Pages;

use App\Filament\Resources\BuyResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditBuy extends EditRecord
{
    protected static string $resource = BuyResource::class;
    protected ?string $heading='تعديل فاتورة شراء';
    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
    protected function getRedirectUrl(): string
    {
        return static::getResource()::getUrl('index');
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {
        $record=$this->getRecord();
        info($record);

        Notification::make()
            ->warning()
            ->title('You don\'t have an active subscription!')
            ->body('Choose a plan to continue.')
            ->persistent()

            ->send();

        $this->halt();
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
